# Generated by Django 4.2 on 2023-04-18 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='Yogesh', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.TextField(blank=True)),
                ('jid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.user1')),
            ],
        ),
    ]
