# Generated by Django 4.2 on 2023-04-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.FloatField(default=1),
        ),
    ]
