# Generated by Django 4.2 on 2023-04-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_box'),
    ]

    operations = [
        migrations.AddField(
            model_name='box',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='box',
            name='volume',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='box',
            name='length',
            field=models.FloatField(default=1),
        ),
    ]
