# Generated by Django 4.2 on 2023-04-19 13:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_box_area_box_volume_alter_box_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to=settings.AUTH_USER_MODEL),
        ),
    ]
